const url = 'http://localhost:3060';
export default {
  register: `${url}/auth/register`,
  login: `${url}/auth/login`,
  logout: `${url}/auth/logout`,
  adminMetas: `${url}/admin/adminMetas`,
  addMeta: `${url}/admin/addMeta`,
  updateMeta: `${url}/admin/updateMeta`,
  adminBasics: `${url}/admin/adminBasics`,
  addBasic: `${url}/admin/addBasic`,
  updateBasic: `${url}/admin/updateBasic`,
  adminBlogs: `${url}/admin/adminBlogs`,
  adminMedia: `${url}/admin/adminMedia`,
  updateMedia: `${url}/admin/updateMedia`,
  adminLeads: `${url}/admin/adminLeads`,
  updateLeads: `${url}/admin/updateLeads`,
  changeLeadStatus: `${url}/admin/changeLeadStatus`,
  addBlog: `${url}/admin/addBlog`,
  updateBlog: `${url}/admin/updateBlog`,
  blogMetaOptions: `${url}/admin/blogMetaOptions`,
  getBlog: `${url}/admin/getBlog/`,
  addPropInputs: `${url}/admin/addPropInputs`,
  adminProperty: `${url}/admin/adminProperty`,
  addProperty: `${url}/admin/addProperty`,
  updateProperty: `${url}/admin/updateProperty`,
  changePropertyStatus: `${url}/admin/changePropertyStatus`,
  getProperty: `${url}/admin/getProperty/`,
  replacePropertyMedia: `${url}/admin/replacePropertyMedia`,
  addMediaInProperty: `${url}/admin/addMediaInProperty`,
  adminBuilders: `${url}/admin/adminBuilders`,
  addBuilder: `${url}/admin/addBuilder`,
  updateBuilder: `${url}/admin/updateBuilder`,
  property: `${url}/user/property`,
  propertyFilters: `${url}/user/propertyFilters`,
  singleProperty: `${url}/user/singleProperty/`,
  suggestBlogs: `${url}/user/suggestBlogs`,
  subscribe: `${url}/user/subscribe`,
  getHomeBlogs: `${url}/user/getHomeBlogs`,
  addLeads: `${url}/user/addLeads`,
  blogs: `${url}/blog`,
  singleBlog: `${url}/singleBlog/`,
  addComment: `${url}/admin/addComment`,
  adminComments: `${url}/admin/adminComments`,
  updateComment: `${url}/admin/updateComment`,
  changeCommentStatus: `${url}/admin/changeCommentStatus`,

};